services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: university_portal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: university_portal
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    networks:
      - university-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "3000:80" # Exposes port 80 of Nginx to port 3000 on your machine
    networks:
      - university-network

volumes:
  postgres-data:

networks:
  university-network:
